import { acSaving, evSaving, shiftSaving, TARIFF } from './calc'

export const DEMO_NOTE = 'Concept demo · Illustrative data'

export const defaultProfile = {
  name: 'Alex',
  district: 'Sha Tin',
  estate: 'Shing Mun Court',
  block: 'Block B',
  flat: '450 sq ft',
  people: 3,
  acUnits: 2,
  ev: true,
  ebike: false,
  elderly: false,
  caregiver: true,
}

export const weather = {
  tempC: 31,
  humidity: 82,
  uv: 8,
  tonightLowC: 28,
  forecast: [
    { d: 'Sat', hi: 32, lo: 28, icon: 'sun' },
    { d: 'Sun', hi: 33, lo: 28, icon: 'sun' },
    { d: 'Mon', hi: 31, lo: 27, icon: 'cloud-sun' },
    { d: 'Tue', hi: 29, lo: 26, icon: 'rain' },
  ],
}

// Yesterday's smart-meter half-hour data rolled up to hourly kWh (sums to 12.8).
export const hourly = [
  0.35, 0.3, 0.28, 0.27, 0.26, 0.27, 0.3, 0.38, 0.35, 0.3, 0.28, 0.27, 0.29, 0.3, 0.32, 0.38, 0.55, 0.72, 1.2, 1.45,
  1.35, 1.1, 0.88, 0.65,
]

export const breakdown = [
  { key: 'cooling', label: 'Cooling', pct: 58, img: '/img/ac.jpg' },
  { key: 'appliances', label: 'Appliances', pct: 24, img: '/img/washer.jpg' },
  { key: 'other', label: 'Lighting & always-on', pct: 18 },
]

// Last 14 days, with daily max temperature.
export const daily = [
  { d: '20 Sep', kwh: 10.9, t: 29 },
  { d: '21 Sep', kwh: 11.4, t: 30 },
  { d: '22 Sep', kwh: 12.2, t: 31 },
  { d: '23 Sep', kwh: 13.5, t: 32 },
  { d: '24 Sep', kwh: 13.1, t: 32 },
  { d: '25 Sep', kwh: 11.8, t: 30 },
  { d: '26 Sep', kwh: 10.6, t: 28 },
  { d: '27 Sep', kwh: 10.2, t: 28 },
  { d: '28 Sep', kwh: 11.9, t: 30 },
  { d: '29 Sep', kwh: 12.7, t: 31 },
  { d: '30 Sep', kwh: 12.1, t: 31 },
  { d: '1 Oct', kwh: 11.0, t: 30 },
  { d: '2 Oct', kwh: 12.8, t: 31 },
  { d: '3 Oct', kwh: 5.9, t: 31, partial: true },
]

export const bill = {
  period: '15 Aug – 14 Oct',
  daysElapsed: 50,
  daysTotal: 61,
  spentSoFar: 890,
  lastPeriod: 912,
  projected: 1086,
  drivers: [
    {
      key: 'weather',
      label: 'Warmer evenings',
      detail: 'Average evening temperature was 30.4°C vs 28.1°C last period, so your ACs ran ~1.6 h longer each night.',
      hkd: 118,
      icon: 'thermometer',
    },
    {
      key: 'ev',
      label: 'EV charged at peak',
      detail: '9 of 14 charging sessions started between 6 and 9 PM, when the pilot peak rate applies.',
      hkd: 41,
      icon: 'car',
    },
    {
      key: 'dryer',
      label: 'More dryer cycles',
      detail: 'Humidity kept laundry damp: 11 dryer cycles vs 6 last period.',
      hkd: 15,
      icon: 'shirt',
    },
  ],
}

const ac = acSaving({ coolingKwh: 7.4, fromC: 24, toC: 25.5, humidity: weather.humidity })
const ev = evSaving({ sessionKwh: 14 })
const washer = { kwh: 1.6, hkd: shiftSaving(1.6) }
const precool = { kwh: 1.9, hkd: 1.9 * (TARIFF.peak - TARIFF.shoulder) + 1.1 * TARIFF.peak }

// Human-reviewed tip library. `heatSafe: false` tips are never shown during hot-weather warnings
// or to vulnerable households, because they reduce cooling.
export const tipLibrary = [
  {
    id: 'ac-setpoint',
    category: 'cooling',
    icon: 'snowflake',
    time: '7:30 PM',
    title: { en: 'Cool your living room at 25.5°C', hk: '客廳冷氣調至25.5°C', cn: '客厅空调调至25.5°C' },
    detail: { en: 'Set to 25.5°C at 7:30 PM, add a fan', hk: '晚上7:30設定25.5°C，配合風扇', cn: '晚上7:30设定25.5°C，配合风扇' },
    why: `Your AC currently runs at 24°C. Each +1°C saves about 6% of cooling energy at ${weather.humidity}% humidity. Based on yesterday's 7.4 kWh of cooling.`,
    kwh: ac.kwh,
    hkd: ac.hkd,
    points: 30,
    heatSafe: false,
  },
  {
    id: 'ac-dry',
    category: 'cooling',
    icon: 'droplets',
    time: '6:00 PM',
    title: { en: 'Use Dry mode for the first hour', hk: '首小時用抽濕模式', cn: '首小时用除湿模式' },
    detail: { en: 'At 82% humidity, dry mode feels cooler for less', hk: '濕度82%，抽濕更涼更慳電', cn: '湿度82%，除湿更凉更省电' },
    why: 'High humidity makes rooms feel hotter. Dry mode removes moisture using ~30% less power than cool mode, without raising the room temperature.',
    kwh: 0.9,
    hkd: 0.9 * TARIFF.peak,
    points: 20,
    heatSafe: true,
  },
  {
    id: 'ev-offpeak',
    category: 'ev',
    icon: 'plug',
    time: '11:00 PM',
    requires: 'ev',
    title: { en: 'Charge overnight', hk: '夜間充電', cn: '夜间充电' },
    detail: { en: 'Start at 11 PM, ready by 7:00 AM · 80% target', hk: '晚上11時開始，早上7時充滿80%', cn: '晚上11点开始，早上7点充至80%' },
    why: `Moving a 14 kWh session from 7 PM to 11 PM saves ${(TARIFF.peak - TARIFF.offPeak).toFixed(2)} HK$/kWh and takes load off the evening peak.`,
    kwh: ev.kwh,
    hkd: ev.hkd,
    points: 40,
    heatSafe: true,
    mission: 'ev3',
  },
  {
    id: 'washer-late',
    category: 'appliances',
    icon: 'washing',
    time: 'After 11 PM',
    title: { en: 'Run the washer-dryer later', hk: '洗衣乾衣機延後使用', cn: '洗衣烘干机延后使用' },
    detail: { en: 'Use the delay timer, done by 7 AM', hk: '用預約功能，早上7時前完成', cn: '用预约功能，早上7点前完成' },
    why: 'A wash-and-dry cycle uses about 1.6 kWh. Shifting it outside 4–11 PM uses the same energy at a lower rate.',
    kwh: washer.kwh,
    hkd: washer.hkd,
    points: 15,
    heatSafe: true,
  },
  {
    id: 'precool',
    category: 'cooling',
    icon: 'timer',
    time: '5:30 PM',
    title: { en: 'Pre-cool before you get home', hk: '回家前預先降溫', cn: '回家前预先降温' },
    detail: { en: 'Start at 5:30 PM at 26°C, then 25.5°C', hk: '5:30開26°C，回家後25.5°C', cn: '5:30开26°C，到家后25.5°C' },
    why: 'Starting gently before the 6–9 PM rush avoids the AC running flat out at the most expensive time.',
    kwh: precool.kwh,
    hkd: precool.hkd,
    points: 25,
    heatSafe: true,
  },
  {
    id: 'curtains',
    category: 'cooling',
    icon: 'blinds',
    time: '2:00 PM',
    title: { en: 'Close west-facing curtains', hk: '拉埋西斜窗簾', cn: '拉上西晒窗帘' },
    detail: { en: 'Keeps rooms ~2°C cooler by evening', hk: '傍晚室溫低約2°C', cn: '傍晚室温低约2°C' },
    why: 'Afternoon sun on west windows is the biggest heat gain in HK flats. Blocking it lowers the cooling load at peak.',
    kwh: 0.7,
    hkd: 0.7 * TARIFF.peak,
    points: 10,
    heatSafe: true,
  },
]

export const heatSafetyTip = {
  id: 'heat-safety',
  title: { en: 'Stay safe: keep cooling on', hk: '注意安全：保持冷氣開啟', cn: '注意安全：保持空调开启' },
  detail: {
    en: 'Very Hot Weather Warning in force. Comfort first, savings tips that reduce cooling are paused.',
    hk: '酷熱天氣警告生效中，以舒適安全為先，暫停減少冷氣的建議。',
    cn: '酷热天气警告生效中，以舒适安全为先，暂停减少空调的建议。',
  },
}

export const smartAlert = {
  id: 'ac-efficiency',
  title: 'Bedroom AC efficiency down 14%',
  detail: 'It now uses 0.4 kWh more per hour than in June for the same temperature. A coil clean usually fixes this.',
  partnerId: 'accare',
}

export const missions = [
  {
    id: 'ev3',
    title: 'Shift your evening energy',
    detail: 'Complete 3 overnight charging plans',
    target: 3,
    progress: 2,
    points: 60,
    icon: 'calendar',
  },
  {
    id: 'peak7',
    title: 'Peak Hero week',
    detail: 'Keep 4–11 PM use under 7 kWh for 7 days',
    target: 7,
    progress: 5,
    points: 500,
    icon: 'zap',
  },
  {
    id: 'cool5',
    title: 'Comfort at 25.5°C',
    detail: 'Try 25.5°C plus a fan on 5 evenings',
    target: 5,
    progress: 3,
    points: 100,
    icon: 'snowflake',
  },
]

export const categories = [
  { id: 'all', label: 'All', icon: 'grid' },
  { id: 'food', label: 'Food & Coffee', icon: 'coffee' },
  { id: 'charging', label: 'Charging', icon: 'zap' },
  { id: 'home', label: 'Home Services', icon: 'wrench' },
  { id: 'property', label: 'Property & Insurance', icon: 'building' },
  { id: 'experiences', label: 'Experiences', icon: 'ticket' },
]

// tier and commission are CLP-internal fields shown only in the CLP pilot dashboard.
export const partners = [
  {
    id: 'pacific',
    name: 'Pacific Coffee',
    category: 'food',
    tier: 3,
    offer: 'HK$10 off any iced drink',
    window: '6:00 – 9:00 PM',
    points: 100,
    value: 10,
    distance: '180 m',
    x: 58,
    y: 30,
    img: '/img/coffee-lg.jpg',
    icon: 'coffee',
    commission: 'HK$2.5 per redeemed coupon',
    hint: 'Step out while your AC rests during peak.',
  },
  {
    id: 'cafe',
    name: 'Neighbourhood Café',
    category: 'food',
    tier: 3,
    offer: 'HK$20 coffee & bun set voucher',
    window: 'All day',
    points: 200,
    value: 20,
    distance: '350 m',
    x: 40,
    y: 22,
    img: '/img/coffee-lg.jpg',
    icon: 'coffee',
    commission: 'HK$3 per redeemed coupon',
  },
  {
    id: 'maxims',
    name: "Maxim's MX",
    category: 'food',
    tier: 3,
    offer: 'HK$10 off dinner sets',
    window: '6:00 – 9:00 PM',
    points: 100,
    value: 10,
    distance: '420 m',
    x: 72,
    y: 58,
    icon: 'utensils',
    commission: 'HK$2 per redeemed coupon',
  },
  {
    id: 'shell',
    name: 'Shell Recharge',
    category: 'charging',
    tier: 2,
    offer: '15% off off-peak charging sessions',
    window: '11 PM – 7 AM',
    points: 150,
    value: 15,
    distance: '600 m',
    x: 22,
    y: 36,
    img: '/img/charger.jpg',
    icon: 'zap',
    commission: 'HK$5 flat fee per redirected session',
  },
  {
    id: 'cornerstone',
    name: 'Cornerstone e-Charge',
    category: 'charging',
    tier: 2,
    offer: 'HK$15 bonus charging credit (EV & e-bike)',
    window: 'Off-peak',
    points: 150,
    value: 15,
    distance: '900 m',
    x: 86,
    y: 40,
    img: '/img/charger.jpg',
    icon: 'zap',
    commission: 'HK$5 flat fee per redirected session',
  },
  {
    id: 'accare',
    name: 'AC Care HK',
    category: 'home',
    tier: 1,
    offer: 'HK$100 off chemical coil cleaning',
    window: 'Book any day',
    points: 300,
    value: 100,
    cofunded: true,
    distance: '1.1 km',
    x: 30,
    y: 70,
    img: '/img/ac.jpg',
    icon: 'wrench',
    commission: '10% referral on booked service',
    hint: 'Recommended: your bedroom AC efficiency has dropped.',
  },
  {
    id: 'fortress',
    name: 'Fortress',
    category: 'home',
    tier: 1,
    offer: 'HK$150 off inverter AC upgrades',
    window: 'Online & in store',
    points: 300,
    value: 150,
    cofunded: true,
    distance: '1.4 km',
    x: 64,
    y: 80,
    img: '/img/ac.jpg',
    icon: 'air-vent',
    commission: '10% referral on appliance purchase',
  },
  {
    id: 'broadway',
    name: 'Broadway',
    category: 'home',
    tier: 1,
    offer: 'HK$150 off heat-pump washer-dryers',
    window: 'Online & in store',
    points: 300,
    value: 150,
    cofunded: true,
    distance: '1.5 km',
    x: 48,
    y: 88,
    img: '/img/washer.jpg',
    icon: 'washing',
    commission: '10% referral on appliance purchase',
  },
  {
    id: 'kaishing',
    name: 'Kai Shing Management',
    category: 'property',
    tier: 4,
    offer: 'HK$50 rebate on monthly management fee',
    window: 'Next billing cycle',
    points: 500,
    value: 50,
    distance: 'Your estate',
    x: 60,
    y: 64,
    icon: 'building',
    commission: '5% affiliate fee on service extensions',
  },
  {
    id: 'insure',
    name: 'HomeSafe Insurance',
    category: 'property',
    tier: 4,
    offer: '20% off home & appliance cover',
    window: 'First year',
    points: 250,
    value: 25,
    cofunded: true,
    distance: 'Online',
    x: 12,
    y: 58,
    icon: 'shield',
    commission: '5% affiliate fee on policy renewals',
  },
  {
    id: 'museum',
    name: 'HK Heritage Museum',
    category: 'experiences',
    tier: 3,
    offer: '2-for-1 entry, cool afternoons indoors',
    window: '1:00 – 6:00 PM',
    points: 120,
    value: 12,
    distance: '800 m',
    x: 78,
    y: 18,
    icon: 'ticket',
    commission: 'HK$3 per redeemed ticket',
  },
  {
    id: 'ecowalk',
    name: 'Shing Mun River Eco-walk',
    category: 'experiences',
    tier: 3,
    offer: 'Free guided evening walk + drink',
    window: 'Sat 7:00 PM',
    points: 80,
    value: 8,
    distance: '250 m',
    x: 18,
    y: 50,
    icon: 'leaf',
    commission: 'Sponsored by partner',
  },
]

export const funds = [
  {
    id: 'clp-re',
    name: 'Asia Renewables Fund',
    tag: 'Wind & solar · APAC',
    risk: 'Medium',
    ret: 6.8,
    color: '#12329a',
    series: [100, 101.2, 100.8, 102.6, 103.9, 103.1, 105.2, 106.4, 105.9, 107.3, 108.1, 109.6],
  },
  {
    id: 'hk-solar',
    name: 'HK Rooftop Solar Notes',
    tag: 'Feed-in Tariff projects · HK',
    risk: 'Low',
    ret: 3.9,
    color: '#2fbf71',
    series: [100, 100.3, 100.7, 101, 101.3, 101.6, 102, 102.3, 102.7, 103, 103.3, 103.9],
  },
  {
    id: 'grid-tech',
    name: 'Clean Grid Tech Index',
    tag: 'Storage, EV, smart grid',
    risk: 'High',
    ret: 11.2,
    color: '#8a8f98',
    series: [100, 97.8, 101.5, 104.2, 99.6, 103.8, 108.9, 106.1, 110.4, 108.7, 112.6, 111.2],
  },
]

export const community = {
  estate: 'Shing Mun Court',
  goalKwh: 5000,
  savedKwh: 3420,
  households: 412,
  participating: 268,
  reward: 'Every 1,000 kWh saved funds 20 fans for elderly neighbours via CLP Community Energy Saving Fund',
  fansFunded: 68,
  blocks: [
    { name: 'Block A', kwh: 1105, households: 96 },
    { name: 'Block B', kwh: 1210, households: 88, mine: true },
    { name: 'Block C', kwh: 655, households: 52 },
    { name: 'Block D', kwh: 450, households: 32 },
  ],
  feed: [
    { who: '18/F neighbour', what: 'charged their e-bike overnight', when: '8 min ago', cheers: 12 },
    { who: '7/F family', what: 'finished a Peak Hero week', when: '1 h ago', cheers: 31 },
    { who: 'Block A caretaker', what: 'switched lobby lights to sensors', when: '3 h ago', cheers: 54 },
    { who: '22/F neighbour', what: 'tried 25.5°C + fan for the first time', when: 'Yesterday', cheers: 9 },
  ],
  weekly: [380, 410, 455, 520, 610, 1045],
}

export const caregiver = {
  name: 'Mum (Mrs Chan)',
  district: 'Wong Tai Sin',
  status: 'All normal',
  lastActivity: 'Kettle used at 8:12 AM',
  acNow: 'Living room AC on · 26°C',
  todayKwh: 4.1,
  usualKwh: 4.4,
  alerts: [
    { level: 'ok', text: 'AC is on during hot weather. Good, she is staying cool.' },
    { level: 'ok', text: 'Morning routine detected (kettle, rice cooker).' },
    { level: 'info', text: 'Bill on track: HK$486 projected, within her HK$550 budget.' },
  ],
}

export const pilot = {
  households: 1000,
  control: 1000,
  week: 9,
  weeks: 12,
  kpis: [
    { id: 'peak', label: 'Evening-peak use vs control', value: '-6.7%', target: 'Target 5–8% lower', ok: true },
    { id: 'ev', label: 'EV charging moved off-peak', value: '68%', target: 'Target ≥ 60%', ok: true },
    { id: 'wau', label: 'Weekly active users', value: '47%', target: 'Target ≥ 40%', ok: true },
    { id: 'tips', label: 'Tips acted on', value: '33%', target: 'Target ≥ 30%', ok: true },
    { id: 'saving', label: 'Avg verified saving / household', value: 'HK$58', target: 'Verified vs control', ok: true },
    { id: 'redeem', label: 'Reward redemption rate', value: '41%', target: 'Monitored', ok: true },
    { id: 'repeat', label: 'Partner repeat rate', value: '27%', target: 'Monitored', ok: true },
  ],
  // Average 4–11 PM kWh per household, by pilot week.
  peakTreatment: [7.6, 7.4, 7.2, 7.1, 7.0, 6.9, 6.9, 6.8, 6.8],
  peakControl: [7.6, 7.6, 7.5, 7.6, 7.5, 7.4, 7.4, 7.3, 7.3],
  evByHour: [
    { h: '6–9 PM', before: 52, now: 18 },
    { h: '9–11 PM', before: 21, now: 14 },
    { h: '11 PM–7 AM', before: 27, now: 68 },
  ],
  cohorts: [
    { label: 'EV owners (n=104)', peak: '-9.1%' },
    { label: 'Elderly residents (n=162)', peak: '-2.4%', note: 'Cooling never reduced; savings from timing only' },
    { label: 'Budget-alert users (n=211)', peak: '-7.3%' },
  ],
  partnerRevenue: [
    { tier: 'Tier 1 · Smart Home & HVAC', partners: 3, redemptions: 146, revenue: 21900 },
    { tier: 'Tier 2 · E-mobility', partners: 2, redemptions: 612, revenue: 3060 },
    { tier: 'Tier 3 · Estate & Neighbourhood', partners: 4, redemptions: 1934, revenue: 4835 },
    { tier: 'Tier 4 · Property & Services', partners: 2, redemptions: 88, revenue: 2640 },
  ],
  roadmap: [
    { phase: 'Pilot', when: 'Summer · 12 weeks', text: '1,000 households in 2 Sha Tin estates, 5–10 partners, matched control group.' },
    { phase: 'Scale', when: 'Next summer', text: 'All CLP app users with smart meters.' },
    { phase: 'Connect', when: 'Year 2', text: 'Smart-home device control and an open partner API.' },
    { phase: 'Automate', when: 'Year 3', text: 'Opt-in automated demand response on hot-weather peaks.' },
  ],
}

export const initialLedger = [
  { id: 'l1', label: 'Overnight charging', pts: 40, when: 'Yesterday' },
  { id: 'l2', label: 'Washer after 11 PM', pts: 15, when: 'Yesterday' },
  { id: 'l3', label: 'Comfort at 25.5°C', pts: 30, when: '1 Oct' },
  { id: 'l4', label: 'Welcome bonus', pts: 155, when: '28 Sep' },
]
